### ISSUE TITLE
NumPy seeding

### ISSUE THREAD

**Issue by rgemulla** [uma-pi1/kge#100]
bdb078f62560b9ebb4be568358e5d04b8d5d7f33 looks broken. Now every worker seems to get the same seed and thus the same sequence of random numbers when a manual seed is specified. This needs to be prevented, e.g., by reseeding based on current seed and worker number.

**Comment by samuelbroscheit** [comment]
The proposed solution relies on the assumption that worker#k always gets the same input which relies on the OS scheduling and speed by which workers are processing their tasks which would not be the same on different machines, right? This would break the main purpose of manual seeding (for me) is to observe regressions between commits. Because then workers with diff seeds get different inputs.

Another question, why was the the commit that broke manual seeding (https://github.com/uma-pi1/kge/commit/9f9e12fe67d146638d7763dd3513dedf0719f39a) only seeding numpy and not python's and torch's RNG as well?

**Comment by rgemulla** [comment]
torch takes care of reseedings its workers, but numpy does not. Using the same seed at every worker is highly flawed: it produces biased results. If reproducabilty is key, use only one worker. (Even with this flawed approach, there is no guarantee of equal outputs as workers may have different speeds.)

**Comment by rgemulla** [comment]
I pushed a small change such that workers use different seeds across different data loaders (6afbf8daef76cca8eb6064946397503c4ba3463c). Please close if this addresses the issue.

**Comment by samuelbroscheit** [comment]
I had already adressed it. Your commit had a few flaws, see comments in commit.

**Comment by rgemulla** [comment]
Thanks, now applied to all data loaders.
