### ISSUE TITLE
The reciprocal relations model cannot compute undirected spo scores

### ISSUE THREAD

**Issue by Demirrr** [uma-pi1/kge#201]
Hello all,

I seem to do not understand this exception "_The reciprocal relations model cannot compute undirected spo scores_" at computing scores of triples via [score_spo](https://github.com/uma-pi1/kge/blob/d0634774b1b29afc739454737aa105dec6cb60b2/kge/model/reciprocal_relations_model.py#L60). Training a model on a set of triples that is augmented with reciprocal relations does not play a role at computing scores of triples, does it?

I seem to circumvent this issue by replacing the exception with `return super().score_spo(s, p, o, "o")` since I simply would like a model to assign a score to a given triple. However, I was wondering whether this workaround has an impact on computations of scores in the current implementation?

Cheers

**Comment by rgemulla** [comment]
The reason is that such models assign two scores for each triple: one using the original relation and one using the inverse relation. Since these two scores can be different, it's unclear which one is requested. LibKGE requires users to specify the `direction` as `"s"` or, as in your workaround, `"o"`. There is no default direction to make users aware that they may do something questionable. Does that clarify?

**Comment by Demirrr** [comment]
Yes, it does. Thank you!
