### ISSUE TITLE
Dealing with tie-handling errors

### ISSUE THREAD

**Issue by BugsBuggy** [uma-pi1/kge#242]
Hello together,
I saw the previous history of tie-handling errors during evaluation in #224. I am still getting those errors during evaluation for example when trying to reproduce the exact same config from iclr20 random search with DistMult on FB15k-237 with negative sampling. I tried to increase the tolerance levels to `atol: 1e-03` and `rtol: 1e-02` but that did not help. I could not figure out smaller values for `rtol` and `atol` yet which do not result in tie-handling errors over many runs.

Are there any best practices on how to set these parameters or other ways to avoid these issues?

**Comment by AdrianKs** [comment]
Issues with tie-handling are treated as a warning now and will not abort the train/eval job. Additionally with #222 we changed the calculation of the scores of the positive triples so that we hopefully don't see the discrepancies between ties anymore. 
You can try again using the default settings for the tolerances.

**Comment by AdrianKs** [comment]
I will close this issue for now, please reopen if this issue still occurs.
