### ISSUE TITLE
fixed_parameters may be ignored

### ISSUE THREAD

**Issue by rgemulla** [uma-pi1/kge#34]
The new fixed_parameters feature below is only applied when num_sobol_trials is set. Perhaps the best approach is to change our implementation to always create the generation_strategy manually (i.e., also when num_sobol_trials=-1).

https://github.com/uma-pi1/kge/blob/0871f68e13da4f80bdf94928cb1eb3001e7058ae/kge/config-default.yaml#L212

**Comment by samuelbroscheit** [comment]
1. Should we remove this feature? It didn't work well when we tested it and because of the rapidly changing of Ax I am not even sure if this is still working correctly. 

2. What about your suggestion to always create the generation strategy ourselves? On the one hand I think its fine to dispatch that to Ax, but on the other hand, due to changes of Ax, this could mean that semantics of a config might change.

**Comment by rgemulla** [comment]
I'd say to remove the feature for now.

**Comment by rgemulla** [comment]
Removed in  692bbda
