### ISSUE TITLE
Support for different tie-breaking schemes

### ISSUE THREAD

**Issue by DbCrWk** [uma-pi1/kge#96]
Currently, ties are handled in a fairly straightforward way:

https://github.com/uma-pi1/kge/blob/75c45ec1c86d9f72027f9d8b7e046bcb38f35c19/kge/job/entity_ranking.py#L547

In short, all triples that have the same score are assigned the same rank. This rank is the "average rank" of the set of triples.

However, based on a recent paper, [A Re-evaluation of Knowledge Graph Completion Methods](https://arxiv.org/pdf/1911.03903.pdf) for more information, there seems to be some merit to allowing for either custom, pre-defined, or the RANDOM tie-breaking procedure. At the very least, it might be nice to explicitly clarify the tie-breaking procedure in configuration, since tie-breaking does strongly influence results for certain models.

**Comment by rgemulla** [comment]
Thanks! I am closing #21 (a dup) because this issues here provides more context.

Generally, the ranking we use in evaluation is fair in that it does not lead to the inflated performance numbers that plague some other implementations. 

Personally, I am not fond of "random" evaluation results. A better way would be to report the expected metric; that's what's approximated by RANDOM in the paper you mention and it can be exactly computed for MRR/Hits@k.

As always, PRs are welcome!

**Comment by DbCrWk** [comment]
@rgemulla I agree with you (and as you mention, the current method is precisely the expectation of the RANDOM method).

I should have been more clear in my original post: I'm advocating for adding a tie-breaking (or ranking) configuration option, not necessarily even implementing these options in LibKGE. That way, anyone looking at an assignment configuration file will know how ties are handled and it will be more clear that this is, in fact, being handled in a consistent and fair manner. In other words, this paper points out that tie-breaking procedures seem to have a strong enough effect that it is worth notating explicitly what tie-breaking procedure was used when running an experiment.

**Comment by rgemulla** [comment]
That's a good, quick to do suggestion.

Note that what LigKGE currently does is not equivalent to the expectation of the RANDOM method. This is because computing a metric using expected rank (which we do) and computing the expected metric (which RANDOM approximates) is generally different since the metrics are not linear in the rank.

**Comment by DbCrWk** [comment]
@rgemulla awesome!

I think I may have some misunderstanding about what RANDOM is doing and I'll defer to you in this matter.

**Comment by rgemulla** [comment]
Addressed by #110

**Comment by DbCrWk** [comment]
thanks!
